name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v3
      - name: build-tools
        run: sdkmanager "build-tools;29.0.3"
      - name: Add Android SDK to PATH
        run: echo "${ANDROID_HOME}/build-tools/29.0.3" >> $GITHUB_PATH

      - name: Grant execute permissions
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew deploy

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MlogWatcher built by action
          path: build/libs/[!raw-]*.jar
